version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${rdr2}
      POSTGRES_PASSWORD: ${8a7cgwh4ausd_#EGsa}

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres

  bot:
    build:
      context: ./Bot
      dockerfile: Dockerfile
    depends_on:
      - postgres