version: '3.4'

services:
  nginx:
    image: nginx:stable-perl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend

  frontend:
    build:
      context: ./React SPA
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app