version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - BOT_TOKEN=${BOT_TOKEN}